/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Log_In_Services;

import Background.Bugs;
import Background.Domain_Validator;
import Interfaces.Notification_Windows.Admin_Account;
import My_SQL.Connector;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jayashanka Deshan
 */
public class Local_Account extends javax.swing.JFrame {

    /**
     * Creates new form Local_Account
     */
    public Local_Account() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/Images/top_menu_48px.png")).getImage());
    }
    
    public void close()
    {
        WindowEvent new_event;
        
        new_event = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new_event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        aname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 30)); // NOI18N
        jLabel1.setText("NEW ADMIN ACCOUNT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 494, 60));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Email Address :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 155, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Admin Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 155, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Smart ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 168, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Mobile Phone Number : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 303, 209, 40));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Password :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, 155, 40));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Retype Password : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 429, 168, 40));

        sid.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        sid.setBorder(null);
        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sidKeyReleased(evt);
            }
        });
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 114, 383, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 157, 383, 10));

        aname.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        aname.setBorder(null);
        getContentPane().add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 179, 383, 40));

        email.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        email.setBorder(null);
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 242, 383, 40));

        number.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        number.setBorder(null);
        number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberKeyReleased(evt);
            }
        });
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 305, 383, 40));

        jTextField6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jTextField6.setBorder(null);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 431, 383, 40));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 409, 383, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 220, 383, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 283, 383, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 346, 383, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 472, 383, 10));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login_rounded_up_30px.png"))); // NOI18N
        jLabel10.setText("CREATE ACCOUNT");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, 60));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear_symbol_30px.png"))); // NOI18N
        jLabel11.setText("CLEAR FIELDS");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_window_30px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, 30));

        jPasswordField1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 380, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SG-Blog-TrdShw-PR-P1_480x480.gif"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 400, 310));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background_01.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        
        close();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void sidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyReleased
        
        int validation = validation_card();
        
        if(validation == 0)
        {
            //dO NOTHING
        }
        else
        {
            JOptionPane.showMessageDialog(null,"That Card Alrady Used!!");
            
            sid.setText("");
        }
    }//GEN-LAST:event_sidKeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        
        int password_validate = password_Validate();
        
        if((jPasswordField1.getText().length() == jTextField6.getText().length()) && (password_validate == 0))
        {
            JOptionPane.showMessageDialog(null,"Password Can't Verify , Please Check Again");
            
            jTextField6.setText("");
        }        
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        
        Register_Admin();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        
        clear_fields();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        
        String nic = email.getText();
        
        if(nic.matches("^[a-zA-Z0-9.@]*$") && Domain_Validator.Matcher(nic) == 1)
        {
            System.out.println("Match");
            
            email.setForeground(Color.BLACK);
        }
        else
        {
             System.out.println("Not Match");
             
             email.setForeground(Color.RED);
        }
    }//GEN-LAST:event_emailKeyReleased

    private void numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberKeyReleased
        
        int number_ = number.getText().length();
        
        if(number_ == 10)
        {
            number.setForeground(Color.BLACK);
        }
        else
        {
            number.setForeground(Color.RED);
        }
    }//GEN-LAST:event_numberKeyReleased

    public void Register_Admin()
    {
        String smart_id = sid.getText();
        
        String admin_name = aname.getText();
        
        String email_  = email.getText();
        
        String voice = number.getText();
        
        int validate = password_Validate();
        
        String password = null;
        
        if(validate == 1)
        {
            password = jTextField6.getText();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"PASSWORDS CAN'T VERIFY CHECK AGAIN");
        }
        
        Connection connection  = Connector.connection();
        
        String SQL = "INSERT INTO STAFF VALUES ('"+smart_id+"','"+admin_name+"','"+password+"','"+email_+"','"+voice+"');";
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           JOptionPane.showMessageDialog(null,"OPERATION FINISHD : New Admin Account Add To System");
           
           close();
        }
        catch(SQLException ERROR)
        {
            JOptionPane.showMessageDialog(null,"ERROR : "+ERROR);
            
            Bugs.exceptions(String.valueOf(ERROR));
        }
    }
    
    public static int password_Validate()
    {
        String password = jPasswordField1.getText();
        
        String password_01 = jTextField6.getText();
        
        if(password.equals(password_01))
        {
            return 1;
        }
        else
        {
            return 0;
        }
    }
    
    public int validation_card()
    {
        Connection connection = Connector.connection();
        
        String SQL = "SELECT * FROM STAFF WHERE Admin_ID ="+Integer.valueOf(sid.getText())+"; ";
        
            Statement stmt = null;
            
            ResultSet rs = null;
            
        try
        {
            stmt = connection.createStatement();
            
            rs = stmt.executeQuery(SQL);
                       
            if(!rs.next())
            {
                System.out.print("0");
                
                return 0;
            }
            else
            {
                System.out.print("1");
                
                return 1;
            }
        }
        catch(SQLException ERROR)
        {
            Bugs.exceptions(String.valueOf(ERROR));
            
            return 0;
        }
    }

    
    public void clear_fields()
    {
        sid.setText("");
        
        aname.setText("");
        
        email.setText("");
        
        number.setText("");
        
        jPasswordField1.setText("");
        
        jTextField6.setText("");
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aname;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public static javax.swing.JTextField jTextField6;
    private javax.swing.JTextField number;
    private javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
