/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Install_Wizard;

import Background.Bugs;
import Background.Domain_Validator;
import First_Launch.Check_Directory;
import My_SQL.Connector;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Jayashanka Deshan
 */
public class Admin_Account extends javax.swing.JInternalFrame {

    /**
     * Creates new form icon
     */
    public Admin_Account()
    {
        initComponents();
        
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        
        BasicInternalFrameUI bis = (BasicInternalFrameUI) this.getUI();
        
        bis.setNorthPane(null);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        aname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField6 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(989, 492));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setText("CREATE FIRST ADMIN ACCOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, 494, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        jLabel4.setText("Smart ID :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, 168, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        jLabel5.setText("Admin Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, 155, 40));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        jLabel6.setText("Email Address :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, 155, 40));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        jLabel7.setText("Mobile Phone Number : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 242, -1, 40));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        jLabel8.setText("Password :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 300, 155, 40));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        jLabel9.setText("Retype Password : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 360, 168, 40));

        sid.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        sid.setBorder(null);
        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sidKeyReleased(evt);
            }
        });
        jPanel1.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 62, 383, 40));

        aname.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        aname.setBorder(null);
        jPanel1.add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 120, 383, 40));

        email.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        email.setBorder(null);
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 180, 383, 40));

        number.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        number.setBorder(null);
        number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberKeyReleased(evt);
            }
        });
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 242, 383, 40));

        jPasswordField1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 300, 383, 40));

        jTextField6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jTextField6.setBorder(null);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 360, 383, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 103, 383, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 161, 383, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 221, 383, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 284, 383, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 341, 383, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 401, 383, 10));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/erase_30px.png"))); // NOI18N
        jLabel11.setText("CLEAR FIELDS");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 417, -1, 60));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/microsoft_admin_30px.png"))); // NOI18N
        jLabel10.setText("CREATE ACCOUNT");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 417, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/First_Launch/giphy (1).gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 400, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        Register_Admin();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        clear_fields();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased

        int password_validate = password_Validate();

        if((jPasswordField1.getText().length() == jTextField6.getText().length()) && (password_validate == 0))
        {
            JOptionPane.showMessageDialog(null,"Password Can't Verify , Please Check Again");

            jTextField6.setText("");
        }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberKeyReleased

        int number_ = number.getText().length();

        if(number_ == 10)
        {
            number.setForeground(Color.BLACK);
        }
        else
        {
            number.setForeground(Color.RED);
        }
    }//GEN-LAST:event_numberKeyReleased

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased

        String nic = email.getText();

        if(nic.matches("^[a-zA-Z0-9.@]*$") && Domain_Validator.Matcher(nic) == 1)
        {
            System.out.println("Match");

            email.setForeground(Color.BLACK);
        }
        else
        {
            System.out.println("Not Match");

            email.setForeground(Color.RED);
        }
    }//GEN-LAST:event_emailKeyReleased

    private void sidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyReleased

        int validation = validation_card();

        if(validation == 0)
        {
            //dO NOTHING
        }
        else
        {
            JOptionPane.showMessageDialog(null,"That Card Alrady Used!!");

            sid.setText("");
        }
    }//GEN-LAST:event_sidKeyReleased
    
    public void Register_Admin()
    {
        String smart_id = sid.getText();
        
        String admin_name = aname.getText();
        
        String email_  = email.getText();
        
        String voice = number.getText();
        
        int validate = password_Validate();
        
        String password = null;
        
        if(validate == 1)
        {
            password = jTextField6.getText();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"PASSWORDS CAN'T VERIFY CHECK AGAIN");
        }
        
        Connection connection  = Connector.connection();
        
        String SQL = "INSERT INTO STAFF VALUES ('"+smart_id+"','"+admin_name+"','"+password+"','"+email_+"','"+voice+"');";
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           new Interfaces.Notification_Windows.Admin_Account().setVisible(true);
           
           Check_Directory.create_file();
                      
        }
        catch(SQLException ERROR)
        {
            JOptionPane.showMessageDialog(null,"ERROR : "+ERROR);
            
            Bugs.exceptions(String.valueOf(ERROR));
        } 
        catch (IOException ex)
        {
            Bugs.exceptions(String.valueOf(ex));
        }
    }

     public static int password_Validate()
    {
        String password = jPasswordField1.getText();
        
        String password_01 = jTextField6.getText();
        
        if(password.equals(password_01))
        {
            return 1;
        }
        else
        {
            return 0;
        }
    }
    
    public int validation_card()
    {
        Connection connection = Connector.connection();
        
        String SQL = "SELECT * FROM STAFF WHERE Admin_ID ="+Integer.valueOf(sid.getText())+"; ";
        
            Statement stmt = null;
            
            ResultSet rs = null;
            
        try
        {
            stmt = connection.createStatement();
            
            rs = stmt.executeQuery(SQL);
                       
            if(!rs.next())
            {
                System.out.print("0");
                
                return 0;
            }
            else
            {
                System.out.print("1");
                
                return 1;
            }
        }
        catch(SQLException ERROR)
        {
            Bugs.exceptions(String.valueOf(ERROR));
            
            return 0;
        }
    }

    
    public void clear_fields()
    {
        sid.setText("");
        
        aname.setText("");
        
        email.setText("");
        
        number.setText("");
        
        jPasswordField1.setText("");
        
        jTextField6.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aname;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public static javax.swing.JTextField jTextField6;
    private javax.swing.JTextField number;
    private javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
