/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Background.Bugs;
import Interfaces.Notification_Windows.Register_Complete;
import Interfaces.Notification_Windows.Register_Fail;
import Interfaces.Notification_Windows.duplicate_found;
import Interfaces.Notification_Windows.Agreement;
import static Background.Cache_Reader.reader;
import Background.Domain_Validator;
import E_Mail.email_thread_common;
import static Interfaces.home.pane;
import My_SQL.Card_Validation;
import My_SQL.Connector;
import My_SQL.Organization_DB;
import My_SQL.Payment_Verification;
import My_SQL.User_Validation;
import Online_Services.Connect_Online;
import SQLite_03.Load_Settings;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import static java.lang.System.load;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Jayashanka Deshan
 */
public class new_member extends javax.swing.JInternalFrame {

    int slot_1 = 0;
    
    int slot_2 = 0;
    
    int slot_3 = 0;
    
    int slot_4 = 0;
    
    int slot_5 = 0;
    
    int slot_7 = 0;
    
    int slot_8 = 0;
    
    
    public new_member() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        
        BasicInternalFrameUI bis = (BasicInternalFrameUI) this.getUI();
        
        bis.setNorthPane(null);
        
        disable_lable();
        
        select.setSelectedItem("Chose Student School");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        index = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        batch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MOB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        NIC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        lable_1 = new javax.swing.JLabel();
        lable_2 = new javax.swing.JLabel();
        lable_3 = new javax.swing.JLabel();
        lable_4 = new javax.swing.JLabel();
        lable_5 = new javax.swing.JLabel();
        lable_6 = new javax.swing.JLabel();
        lable_7 = new javax.swing.JLabel();
        select = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        field_ = new javax.swing.JTextField();
        lable_8 = new javax.swing.JLabel();
        box_1 = new javax.swing.JCheckBox();
        box_2 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        notification = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        card = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();

        jTextField2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jTextField2.setText("jTextField2");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1280, 668));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 30)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animations/955-demand-outline (1).gif"))); // NOI18N
        jLabel1.setText("ADD MEMBERS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animations/333-loader-4.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 80, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Mobile Number   : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, 185, -1));

        uname.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        uname.setToolTipText("Allow Only Words ");
        uname.setBorder(null);
        uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unameKeyReleased(evt);
            }
        });
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 88, 345, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("SLTC Index          :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 185, -1));

        index.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        index.setBorder(null);
        index.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                indexKeyReleased(evt);
            }
        });
        jPanel1.add(index, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 20, 345, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("User Name          :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 185, -1));

        batch.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        batch.setBorder(null);
        batch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                batchKeyReleased(evt);
            }
        });
        jPanel1.add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 418, 345, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Related Class     :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 418, 185, -1));

        MOB.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        MOB.setToolTipText("Numarical Data Only");
        MOB.setBorder(null);
        MOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBActionPerformed(evt);
            }
        });
        MOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MOBKeyReleased(evt);
            }
        });
        jPanel1.add(MOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 154, 345, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel7.setText("E mail Address    :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 185, -1));

        mail.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        mail.setBorder(null);
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
        });
        jPanel1.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 220, 345, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel8.setText("NIC Number        :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, 185, -1));

        NIC.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        NIC.setBorder(null);
        NIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NICKeyReleased(evt);
            }
        });
        jPanel1.add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 286, 345, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Related School    :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 352, 185, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 53, 345, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 119, 345, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 185, 345, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 251, 345, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 317, 345, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 449, 345, 10));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 20, -1, 439));

        lable_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png"))); // NOI18N
        jPanel1.add(lable_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 34));

        lable_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png"))); // NOI18N
        jPanel1.add(lable_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 85, -1, 34));

        lable_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png"))); // NOI18N
        jPanel1.add(lable_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, 34));

        lable_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png"))); // NOI18N
        jPanel1.add(lable_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 215, -1, 34));

        lable_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png"))); // NOI18N
        jPanel1.add(lable_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, 34));

        lable_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png"))); // NOI18N
        jPanel1.add(lable_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 345, -1, 34));

        lable_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png"))); // NOI18N
        jPanel1.add(lable_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, 34));

        select.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Engineering", "School of Technology", "School of Business", "School of Computing & IT", "School of Music" }));
        select.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        select.setFocusable(false);
        select.setOpaque(false);
        select.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                selectKeyReleased(evt);
            }
        });
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 352, 345, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 620, 490));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment_history_32px.png"))); // NOI18N
        jLabel20.setText("Make Payment");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel21.setText("Payment Recipt Number : ");

        field_.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        field_.setBorder(null);
        field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_ActionPerformed(evt);
            }
        });
        field_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_KeyReleased(evt);
            }
        });

        lable_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png"))); // NOI18N

        box_1.setBackground(new java.awt.Color(255, 255, 255));
        box_1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        box_1.setText("USER PAID RELATED REGISTERATION PAYMENTS");
        box_1.setBorder(null);
        box_1.setFocusable(false);
        box_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_1ActionPerformed(evt);
            }
        });

        box_2.setBackground(new java.awt.Color(255, 255, 255));
        box_2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        box_2.setText("USER ACCEPT ALL AGREEMENTS AND TERMS IN THE SLTC LIBRARY");
        box_2.setBorder(null);
        box_2.setFocusable(false);
        box_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registration_32px.png"))); // NOI18N
        jLabel22.setText("Register User");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        notification.setBackground(new java.awt.Color(255, 255, 255));
        notification.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(box_1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(box_2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(2, 2, 2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator10)
                                .addComponent(field_, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lable_8))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lable_8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(box_1)
                .addGap(24, 24, 24)
                .addComponent(box_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161)
                .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 610, 480));

        card.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        card.setBorder(null);
        card.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cardKeyReleased(evt);
            }
        });
        getContentPane().add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 330, 40));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 334, 10));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked

       if(slot_1 == 1 && slot_2 == 1)
       {
           card.setEditable(false);
           
           card.setBackground(Color.WHITE);
           
           index.setEditable(false);
           
           index.setBackground(Color.WHITE);
           
           uname.setEditable(false);
           
           uname.setBackground(Color.WHITE);
           
           Payment_Gateway payment = new Payment_Gateway();
       
           payment.setVisible(true);
            
           try 
           {
               payment.get_data(index.getText(),uname.getText(),"For Registeration Fee",Load_Settings.load_settings("RPAYMENT"),reader("Current_admin.dat"));
           } 
           catch (FileNotFoundException ex) 
           {
               Logger.getLogger(new_member.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else
       {
           notification.setText("Plese Enter Valid Index and Name");
           
           notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
       }
       
    }//GEN-LAST:event_jLabel20MouseClicked

    private void cardKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardKeyReleased
        
       int get_value = Card_Validation.validation_card(Integer.valueOf(card.getText()));
       
       if(get_value == 1)
       {
           card.setText("");
           
           jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animations/333-loader-4.gif")));
           
           duplicate_found found = new duplicate_found();
           
           found.setVisible(true);
       }
       else
       {
           jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animations/20-love-heart-outline.gif")));
           
           jPanel1.setVisible(true);
       }
    }//GEN-LAST:event_cardKeyReleased

    private void MOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOBActionPerformed

    private void indexKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indexKeyReleased
      
        int get_value = User_Validation.validation_userID(index.getText());
        
        if(get_value == 1)
        {
            duplicate_found found = new duplicate_found();
           
            found.setVisible(true);
            
            index.setText("");
        }
        else
        {
            //get_data();
        }
        
         if(Pattern.matches("^[0-9A-Z]+$",index.getText()) && index.getText().length() == 6)
         {
             lable_1.setVisible(true);
             
             lable_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png")));
             
             slot_1 = 1;
         }
         else
         {
             lable_1.setVisible(true);
             
             lable_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
             
             slot_1 = 2;
         }

        System.out.println("SLOT : "+slot_1+"\n\n");
    }//GEN-LAST:event_indexKeyReleased

    private void unameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameKeyReleased

        String name = uname.getSelectedText();
        
         if(Pattern.matches("^[a-zA-Z. ]+$",uname.getText()))
         {
             lable_2.setVisible(true);
             
             lable_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png")));
             
             slot_2 = 1;
         }
         else
         {
             lable_2.setVisible(true);
             
             lable_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
             
             slot_2 = 0;
         }

    }//GEN-LAST:event_unameKeyReleased

    private void MOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MOBKeyReleased
       
       String number = MOB.getText();
                       
        if(number.matches("^[0-9]*$") && number.length()== 10)
        {
            lable_3.setVisible(true);
            
            lable_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png")));
            
            slot_3 = 1;
            
            int get_value = User_Validation.validation_number(Integer.valueOf(MOB.getText()));
            
            if(get_value == 1)
            {
            duplicate_found found = new duplicate_found();
           
            found.setVisible(true);
            
            MOB.setText("");   
            }
        }
        else
        {
            lable_3.setVisible(true);
            
            lable_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
            
            slot_3 =0;
        }
    }//GEN-LAST:event_MOBKeyReleased

    private void NICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICKeyReleased
        
        String nic = NIC.getText();
             
        if(nic.matches("^[0-9A-Za-z]*$") && ((nic.length()== 12) || (nic.length()== 10)))
        {
            lable_5.setVisible(true);
            
            lable_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png")));
            
            slot_5 = 1;
            
            int get_value = User_Validation.validation_NIC(Integer.valueOf(NIC.getText()));
            
            if(get_value == 1)
            {
                duplicate_found found = new duplicate_found();
           
                found.setVisible(true);
            
                NIC.setText("");
            }
        }
        else
        {
            lable_5.setVisible(true);
            
            lable_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
            
            slot_5 = 0;
        }
    }//GEN-LAST:event_NICKeyReleased

    private void selectKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectKeyReleased
        
        if(select.getSelectedItem().equals("Chose Student School"))
        {
            lable_6.setVisible(true);
            
            lable_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
        }
        else
        {
            lable_6.setVisible(true);
            
            lable_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png")));
        }
    }//GEN-LAST:event_selectKeyReleased

    private void batchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchKeyReleased
       
        String nic = batch.getText();
        
        if(nic.matches("^[0-9A-Z]*$") && (nic.length()== 5))
        {
            lable_7.setVisible(true);
            
            lable_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png")));
            
            slot_7 = 1;
        
        }
        else
        {
            lable_7.setVisible(true);
            
            lable_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
            
            slot_7 = 0;
        }
    }//GEN-LAST:event_batchKeyReleased

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyReleased
        
        String nic = mail.getText();
        
        int get_value = User_Validation.validation_EMAIL(nic);
        
        if(get_value == 1)
        {
            duplicate_found found = new duplicate_found();
           
            found.setVisible(true);
            
            mail.setText("");
        }
        
        if(nic.matches("^[a-zA-Z0-9.@]*$") && (Domain_Validator.Matcher(mail.getText()) == 1))
        {
            lable_4.setVisible(true);
            
            lable_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png")));
            
            slot_4 = 1;
        
        }
        else
        {
            lable_4.setVisible(true);
            
            lable_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
            
            slot_4 = 0;
        }
    }//GEN-LAST:event_mailKeyReleased

    private void field_KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_KeyReleased
 
        int value = Payment_Verification.Income_Verification(field_.getText(),index.getText());
        
        if(value == 1)
        {
            lable_8.setVisible(true);
            
            lable_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checked_30px.png")));
            
            field_.setEditable(false);
            
            slot_8 = 1;
        }
        else
        {
            lable_8.setVisible(true);
            
            lable_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel_30px.png")));
            
            slot_8 = 0;
        }
    }//GEN-LAST:event_field_KeyReleased

    private void box_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_1ActionPerformed

    private void box_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_2ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
     
         int choice = JOptionPane.showConfirmDialog(null,"Do You Want To Add This Member");
        
        if(choice == 0)
        {
            Cloud_Sync sync = new Cloud_Sync();
             
            sync.start();
        }
        
    }//GEN-LAST:event_jLabel22MouseClicked

    public class Cloud_Sync implements Runnable
{
    private final Thread thread;
    
    public Cloud_Sync()
    {
        thread = new Thread(this);
    }

        @Override
        public void run() 
        {
        int eid = Integer.valueOf(card.getText());
        
        String name = uname.getText();
        
        String sltc_index = index.getText();
        
        String mobile = MOB.getText();
        
        String email = mail.getText();
        
        String nicc = NIC.getText();
        
        String school = (String) select.getSelectedItem();
        
        String year = batch.getText();
        
        int valid = field_validation();
        
        String SQL = "INSERT INTO library_user VALUES ("+eid+",'"+name+"','"+sltc_index+"','"+mobile+"','"+nicc+"','"+email+"','"+school+"','"+year+"');";
        
        Connection connection =  Connector.connection();
        
        Connection conn = Connect_Online.Online();
        
        if(box_1.isSelected() && box_2.isSelected() && valid == 1)
        {
        try
        {
           PreparedStatement preparedStatement_2 = conn.prepareStatement(SQL);

           preparedStatement_2.executeUpdate();
           
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
         
           email_thread_common send_mail = new email_thread_common(email,name,"User Registeration Notifiaction",reader("Wel_Come.dat"),eid);
          
           send_mail.start();
           
           Register_Complete notification = new Register_Complete();
                
           notification.setVisible(true);
           
           pane.removeAll();
        
           new_member screen_05 = new new_member();
        
           pane.add(screen_05).setVisible(true);
        }
        catch(Exception ERROR)
        {
            notification.setText("CAN'T REGISTER USER");
                
            Register_Fail fail = new  Register_Fail();
                
            fail.setVisible(true);
            
            Bugs.exceptions(String.valueOf(ERROR));
        }
        }
        else
        {
            Agreement fail = new  Agreement();
                
            fail.setVisible(true);
        }

        }   
    public void start()
    {
        thread.start();
    }    
 }
    
    
    public int field_validation()
    {
        
        if((slot_1 == 1)&&(slot_2 == 1)&&(slot_3 == 1)&&(slot_4 == 1)&&(slot_5 == 1)&&(slot_7 == 1)&&(slot_8 == 1))
        {
            return 1;
        }
        else
        {
            return 0;
        }
    }
    
    private void field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_ActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    public void get_data()
    {        
        Connection connect = Organization_DB.connection();
        
        String SQL = "SELECT * FROM STUDENT WHERE STUDENT_INDEX = '"+index.getText()+"';";
        
        try
        {
            Statement stmt = connect.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
                uname.setText(rs.getString("STUDENT_NAME"));
            
                uname.setText(rs.getString("STUDENT_NAME"));
            
                //
            
                batch.setText(rs.getString("BATCH_NUMBER"));
            }    
        }
        catch(SQLException ERROR)
        {
            System.out.println(ERROR);
        }
        
    }
    public void disable_lable()
    {
        lable_1.setVisible(false);
        
        lable_2.setVisible(false);
        
        lable_3.setVisible(false);
        
        lable_4.setVisible(false);
        
        lable_5.setVisible(false);
        
        lable_6.setVisible(true);
        
        lable_7.setVisible(false);
        
        lable_8.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MOB;
    private javax.swing.JTextField NIC;
    private javax.swing.JTextField batch;
    private javax.swing.JCheckBox box_1;
    private javax.swing.JCheckBox box_2;
    private javax.swing.JTextField card;
    public static javax.swing.JTextField field_;
    private javax.swing.JTextField index;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lable_1;
    private javax.swing.JLabel lable_2;
    private javax.swing.JLabel lable_3;
    private javax.swing.JLabel lable_4;
    private javax.swing.JLabel lable_5;
    private javax.swing.JLabel lable_6;
    private javax.swing.JLabel lable_7;
    private javax.swing.JLabel lable_8;
    private javax.swing.JTextField mail;
    public static javax.swing.JLabel notification;
    private javax.swing.JComboBox<String> select;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
