/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Background.Config;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Jayashanka Deshan
 */
public class open_screen extends javax.swing.JInternalFrame {

    /**
     * Creates new form open_screen
     */
    public open_screen() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        
        BasicInternalFrameUI bis = (BasicInternalFrameUI) this.getUI();
        
        bis.setNorthPane(null);
        
       /* Config setting = new Config();
         
        String current_theme = setting.get_properties("theam");
        
        if(current_theme.equals("Abstract White"))
        {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Abstract_White/Screen.jpg")));
            
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/New folder/Color logo - no background.png"))); 
        }
        else if(current_theme.equals("Unicorn"))
        {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Unicorn/Main_Screen.png")));
            
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/New folder/Color logo - no background.png"))); 
        }
        else if(current_theme.equals("Nirvana"))
        {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nirvana/Main_Screen.jpg")));
            
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/New folder/Color logo - no background.png"))); 
        }
        else if(current_theme.equals("Dark Mist"))
        {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark Mist/Main_Screen.png")));
            
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/New folder/White logo - no background.png"))); 
        }
        else if(current_theme.equals("Sky Blue"))
        {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sky Blue/Main_Screen.png")));
            
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/New folder/Color logo - no background.png"))); 
        }
        else if(current_theme.equals("Default"))
        {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nirvana/Main_Screen.jpg")));
            
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/New folder/Color logo - no background.png"))); 
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1280, 668));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logos/New folder/Color logo - no background.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 540));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nirvana/Main_Screen.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1280, 675));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
