/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Background.Bugs;
import PDF.Report_Formatter;
import SQLite_03.SQLite_Connector;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jayashanka Deshan
 */
public class View_Damage extends javax.swing.JFrame {


    String damage_id = null;
    
    public View_Damage(String ID) 
    {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/Images/factory_breakdown_50px.png")).getImage());
        
        this.damage_id = ID;
        
        view_data();
    }

    
    public void view_data()
    {
        String SQL = "SELECT * FROM Damage_Books WHERE Damage_ID = '"+damage_id+"';";
        
        Connection connection = SQLite_Connector.connect_0();
        
         
        try
        {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
                text.append("Damage ID : "+rs.getString("Damage_ID")+"\n\n");
                
                text.append("Memebership ID : "+rs.getString("Membership_id")+"\n\n");
                
                text.append("Book ID : "+rs.getString("Book_id")+"\n\n");
                
                text.append("Payment ID : "+rs.getString("Payment_ID")+"\n\n");
                
                text.append("Fines ID : "+rs.getString("fines")+"\n\n");
                
                text.append("Date : "+rs.getString("Date")+"\n\n");
                
                text.append("Discription : "+rs.getString("Discription")+"\n\n");
                
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(rs.getString("Image")).getImage().getScaledInstance(446,343, Image.SCALE_DEFAULT));
                                        
                jLabel1.setIcon(imageIcon);
            }
        }
        catch(SQLException error)
        {
            Bugs.exceptions(String.valueOf(error));
        }
            
    }
    
    
    
    
    
    public void Report() throws IOException
    {
        String SQL = "SELECT * FROM Damage_Books WHERE Damage_ID = '"+damage_id+"';";
        
        Connection connection = SQLite_Connector.connect_0();
        
         
        try
        {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
  
                Report_Formatter.Report_Generate(rs.getString("Membership_id"),rs.getString("Book_id"),rs.getString("fines"),rs.getString("Payment_ID"),rs.getString("Discription"),rs.getString("Image"));
            }
        }
        catch(SQLException error)
        {
            Bugs.exceptions(String.valueOf(error));
        }
    }

    public void remove()
    {
        String SQL = "DELETE FROM Damage_Books WHERE Damage_ID = '"+damage_id+"';";
        
        Connection connection = SQLite_Connector.connect_0();
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           JOptionPane.showMessageDialog(null,"Successfully Current Item Mark As Repaired");
       
        }
        catch(SQLException ERROR)
        {
            JOptionPane.showMessageDialog(null,"SQL ERROR : \n"+ERROR);
            
            Bugs.exceptions(String.valueOf(ERROR));
        } 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 581, 389));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 57, 446, 343));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Preview Image : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 11, 358, 35));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 406, 1037, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graph_report_30px.png"))); // NOI18N
        jLabel3.setText("Genarate Report");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 427, 150, 39));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_30px.png"))); // NOI18N
        jLabel4.setText("Mark As Repaired ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 427, 159, 39));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_all_tabs_30px.png"))); // NOI18N
        jLabel5.setText("Close This Tab");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 427, 133, 39));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background_01.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
        close();
        
        Damage_Books.table_load();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        int choice = JOptionPane.showConfirmDialog(null,"If You Mark As This Item Repaired It Will Automatically\n\nRemove From Database\n\nAre You Really Want To Marks As Repaired");
        
        if(choice == 0)
        {
            remove();
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        int choice = JOptionPane.showConfirmDialog(null,"Are You Want Genarate Printable Report");
        
        if(choice == 0)
        {
            try
            {
                Report();
            }
            catch(Exception error)
            {
                Bugs.exceptions(String.valueOf(error));
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    public void close()
    {
        WindowEvent new_event;
        
        new_event = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new_event);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
